version: '3.9'

services:
    # Vite
    vite:
        container_name: ${PROJECT}
        build: .
        image: ${PROJECT}:0.1
        ports:
            - 80:5000 # Preview
            - 81:5001 # Dev
        environment:
            HOST: 0.0.0.0
        volumes:
            - .:/home/app
            - /home/app/node_modules
        working_dir: /home/app
        command: npm run dev